### ISSUE TITLE
Compilation of test.nim fails for me on OS X

### ISSUE THREAD

**Issue by oderwat** [StefanSalewski/nim-gdk_pixbuf#1]
Hi. I am getting an error when trying to compile test:
```
test.nim(5, 4) Error: undeclared identifier: 'gdk_pixbuf_get_type'
```
I hat gdk-pixbuf/2.30.8 (installed by homebrew) and thought thats the problem. So I removed that and downloaded gdk-pixbuf-2.31.2, compiled and installed it. Rebuild/installed the nim wrapper again but I still get the same error.

Any Ideas?

**Comment by StefanSalewski** [comment]
Thanks. Yes,  the problem are the when: statements in all the modules. Generally I compile on Linux, so "when defined(unix)" gives true. Then I compile with "-d:windows" to test for windows, and if necessary I try to compile with "-d:macosx". Hoping to catch all combinations. When compiling with -d:windows I generally get a message "external program failed" -- that is because windows.h is not available I guess, but that message ensures at least that Nim itself compiled successfully. A problem may be left defined(unix) is always true on my box. I have no idea if I can change that, so for a test I have to do a text replace in the wrapper files, defined(unix) to false each time I want to test. I think I may forgot that in the past...

**Comment by StefanSalewski** [comment]
Ah, you are right. I removed the "gdk_pixbuf" prefix from the module and forgot to fix the test. Tested only with Aporia.
